sudo: true
language: node_js
node_js:
- node
git:
  quiet: true
cache:
- yarn
- npm
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5383e47cf9c0_key -iv $encrypted_5383e47cf9c0_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
script: echo "skipping test..."
after_success:
- bash ./deploy.sh
env:
  global:
    secure: FWlM5lRzF3T11VWQNUbWoeJGFjqxbw/rl7aGmfA51UHXAlMI3Ql+PE3YBr8nqe8Zuf3jyNqyYM9YhticL7AQque2EeW+azdHOgT9BaRqosxxgruiKQCPKQavTCczA2BngRjbwBY909goACkHb2FOaHRY/jeVy/V+B9IuQHzFCRVi/7uauhbK5KBEShcPQ9ABKjn6x3t1Npg7ZYc3jOZmc32rZcaKlhbBEAfHDExU8cn5/7btg+oNNbJNPrRH8au55vNh5XFjVfyyWtiXpH79QhO9+iFg/bB7NUQVsRyhcCWW8/+aGFYEG5c+w1OFZjPY+VK/KsanBSTHGPv+KVSlsgV8fJZ17dK8JSxv/oi593//VzZcJ7s+/ex5YB6vWpB2DX6VJB+pXKujX1JLc26cUxdtaM1W6HaMKBoHvkDFin0ypyr2YX3rSvMfRqtILrfcTftKtOVwGksYRGqaQgnyRhB09cb9Jh3r9B6lmlMp5MXUjt4keeq1eG1GGerOwnNwVmGNDURGbBjQHcNMIfSlioD7zdRmty3xvLweR7JyLeSCDQJ+RM/NiGUkmBezUHMyNpBz2Heqv5TydM49UlNE7YLCJO4AuUaFDNPCSzws8fYrMhovoDps3Ob/1MkVIqwNojZTIzgxvrGTgQMePMoIrhJ0C2oShjEjPb11PeQh/WM=
